### ISSUE TITLE
Metasploit error termux installation

### ISSUE THREAD

**Issue by Renedwin2** [h4ck3r0/Metasploit-termux#1]
![Screenshot_20220411-044111](https://user-images.githubusercontent.com/84302859/162661629-666da262-7e3b-430b-9978-3d6ea5380ef8.png)

How to fix it please🙏😪😪 l

**Comment by h4ck3r0** [comment]
Clear data your termux and reinstall

**Comment by Renedwin2** [comment]
i have more data  that I don't want to loose

**Comment by h4ck3r0** [comment]
Sorry bro u can't fix it
