### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by Prasanth9618** [h4ck3r0/Metasploit-termux#11]
An error occurred while installing sqlite3

**Comment by h4ck3r0** [comment]
Metasploit is not stable in termux, if you want to fix it give start to my tool,  I will work on it

**Comment by Prasanth9618** [comment]
Ok thank you

**Comment by SikoRDX** [comment]
@h4ck3r0 Hi bro , how long will it take to fix the bug),?

**Comment by Saroj7377** [comment]
> @h4ck3r0 Hi bro , how long will it take to fix the bug),?

nio4r error solved plz vissit for details https://youtu.be/coQPvapS17w
