### ISSUE TITLE
Can't find any ./msfconsole

### ISSUE THREAD

**Issue by Bakare-Ayomide** [h4ck3r0/Metasploit-termux#14]
Ok so I ran all commands and all worked fine and I landed on the metaspoit page. But yet the (./msfconsole) not working cos no option to respond to it.

**Comment by Bakare-Ayomide** [comment]
Ok so I Ran all commands and all worked fine and I landed on the metaspoit page. But yet the (./msfconsole) not working cos no option to respond to it

![Screenshot_20230904-093454](https://github.com/h4ck3r0/Metasploit-termux/assets/137895853/90b721b7-fdfc-4b4d-8853-49f80dd90abe)

**Comment by h4ck3r0** [comment]
Please learn termux basics command and the fact is you are in wrong directory, location should be ~/metasplot-framework

**Comment by Bakare-Ayomide** [comment]
It's alright and thanks sir, I'm still learning the termux basics. But the
issues is that I can't find any directory like that
I saw it on GitHub as you told users to cd to metaspoit-framework and there
./msfconsole but I can't find any directory like that just at all. That why
im actually confused

**Comment by h4ck3r0** [comment]
Then may be metasplot-framework is not installed. Use metasplot-framework in kali linux. Just install it in termux
