### ISSUE TITLE
I can't see any directory as metaspoit-framework 

### ISSUE THREAD

**Issue by Bakare-Ayomide** [h4ck3r0/Metasploit-termux#15]
It's alright and thanks sir, I'm still learning the termux basics. But the issues is that I can't find any directory like that 
I saw it on GitHub as you told users to cd to metaspoit-framework and there ./msfconsole but I can't find any directory like that just at all. That why im actually confused 
![Screenshot_20230904-102615](https://github.com/h4ck3r0/Metasploit-termux/assets/137895853/769b2d21-50d9-47e4-b861-72dad82b9450)

Please if you have a video tutorial about it on YouTube or anywhere I'd appreciate if you can share link.

**Comment by h4ck3r0** [comment]
https://youtu.be/en2O12q0zDw
