### ISSUE TITLE
Bug!!

### ISSUE THREAD

**Issue by kinumaster** [h4ck3r0/Metasploit-termux#16]
ruby (3.2.2)  < new version added
What metasploit.sh uses (2.7.2)

**Comment by h4ck3r0** [comment]
Can you send ss

**Comment by kinumaster** [comment]
The problem was when i use Repiar it just delete it and does not install the new version it just install it self that it.
It is just easy just a bug 
I know you can fix it

**Comment by kinumaster** [comment]
And other thing is when installatio

**Comment by h4ck3r0** [comment]
Bro go to metasploit-framework directory then try

**Comment by kinumaster** [comment]
I do it did not work
And belive me you are the best for me

**Comment by kinumaster** [comment]
also in tmvenom to says msfconsole negative

**Comment by kinumaster** [comment]
Sorry nab problem #%

**Comment by h4ck3r0** [comment]
Bro send screen shot for error and command should be.   . /msfconsole
