### ISSUE TITLE
No database driver installed

### ISSUE THREAD

**Issue by Amadiya69** [h4ck3r0/Metasploit-termux#2]
![Screenshot_20220823-001242](https://user-images.githubusercontent.com/91735688/185996083-80fdee8b-f955-41bb-a649-a9ca1f88758a.jpg)
Resolve this issue

**Comment by h4ck3r0** [comment]
mkdir -p $PREFIX/var/lib/postgresql >/dev/null 2>&1
initdb $PREFIX/var/lib/postgresql 
pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

please give star , we need support
