### ISSUE TITLE
Error in installing metasploit 

### ISSUE THREAD

**Issue by Hacker-cracker32** [h4ck3r0/Metasploit-termux#4]
![Screenshot_20220924-133234_Termux](https://user-images.githubusercontent.com/114204530/192088746-5ae7a2d4-6b7b-4614-9725-d6d95deb9a07.jpg)

**Comment by Hacker-cracker32** [comment]
Nokogiri-1.8.0 is a big problem in it

**Comment by h4ck3r0** [comment]
gem install nokogiri -v '1.8.0' -- --use-system-libraries
