### ISSUE TITLE
ruby: no Ruby script found in input (LoadError)

### ISSUE THREAD

**Issue by EBADSIDD** [h4ck3r0/Metasploit-termux#5]
![IMG_20220925_200518](https://user-images.githubusercontent.com/114259421/192150562-3ecdda2a-e668-4a1e-8d44-d061c3e6e326.jpg)

**Comment by h4ck3r0** [comment]
Go to metasploit folder then run ./msfconsole

**Comment by h4ck3r0** [comment]
Go to metasploit folder then run ./msfconsole
