### ISSUE TITLE
Metasploit termux

### ISSUE THREAD

**Issue by Radha9266** [h4ck3r0/Metasploit-termux#6]
from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException).

How to solve

**Comment by h4ck3r0** [comment]
Reinstall Metasploit may fix this issue and Metasploit is not stable in termux, so no guarantee
