### ISSUE TITLE
Could not find rake-13.0.6 in any of the sources Run `bundle install` to install missing gems.

### ISSUE THREAD

**Issue by Yudhi-sthir** [h4ck3r0/Metasploit-termux#9]
How to slove this problem pls help

**Comment by h4ck3r0** [comment]
Before creating issue, give star that will motivate me to fix the tool

**Comment by h4ck3r0** [comment]
Have u selected option 2 ???

**Comment by Yudhi-sthir** [comment]
No i m select 1

**Comment by h4ck3r0** [comment]
Android version method 1 or 2

**Comment by Yudhi-sthir** [comment]
2

**Comment by h4ck3r0** [comment]
Ok please try again and if you same error report me here and don't forget to give star to my repo

**Comment by Yudhi-sthir** [comment]
Ok bro 
And i already given you star

**Comment by Yudhi-sthir** [comment]
Could not find nokogiri-1.13.10 in any of the sources

**Comment by h4ck3r0** [comment]
Clear cache and data of termyx and reinstall
